### ISSUE TITLE
Not working on Samsung Galaxy S5 SM-G900V Android 6.0.1

### ISSUE THREAD

**Issue by yleyvag** [mvdan/libaccesspoint#17]
I don't know if it's just a problem of Samsung. I test the same application on a BLU smartphone and the access point was created. On Samsung didn't work. I received this exceptions:
E/WifiApControl: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at cc.mvdan.accesspoint.WifiApControl.invokeQuietly(WifiApControl.java:178)
at cc.mvdan.accesspoint.WifiApControl.setWifiApEnabled(WifiApControl.java:250)
at cc.mvdan.accesspoint.WifiApControl.setEnabled(WifiApControl.java:259)
at cc.mvdan.accesspoint.WifiApControl.enable(WifiApControl.java:264)
at cu.yleyvag.quizzdroid.presentation.ui.InviteActivity.onCreate(InviteActivity.java:47)
at android.app.Activity.performCreate(Activity.java:6876)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
at android.app.ActivityThread.access$1100(ActivityThread.java:221)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7224)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: java.lang.SecurityException: ConnectivityService: Neither user 10275 nor current process has android.permission.CONNECTIVITY_INTERNAL.
at android.os.Parcel.readException(Parcel.java:1620)
at android.os.Parcel.readException(Parcel.java:1573)
at android.net.wifi.IWifiManager$Stub$Proxy.setWifiApEnabled(IWifiManager.java:1964)
at android.net.wifi.WifiManager.setWifiApEnabled(WifiManager.java:2192)
at java.lang.reflect.Method.invoke(Native Method) 
at cc.mvdan.accesspoint.WifiApControl.invokeQuietly(WifiApControl.java:178) 
at cc.mvdan.accesspoint.WifiApControl.setWifiApEnabled(WifiApControl.java:250) 
at cc.mvdan.accesspoint.WifiApControl.setEnabled(WifiApControl.java:259) 
at cc.mvdan.accesspoint.WifiApControl.enable(WifiApControl.java:264) 
at cu.yleyvag.quizzdroid.presentation.ui.InviteActivity.onCreate(InviteActivity.java:47) 
at android.app.Activity.performCreate(Activity.java:6876) 
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:158) 
at android.app.ActivityThread.main(ActivityThread.java:7224) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by mvdan** [comment]
Have you seen #6?

**Comment by yleyvag** [comment]
The BLU smartphone is running Android 6.0 and everything is OK.

**Comment by mvdan** [comment]
Have you looked into CONNECTIVITY_INTERNAL, as the exception shows? The library doesn't handle permissions for you.

**Comment by yleyvag** [comment]
I tried to add that permissions but it seems that CONNECTIVTY_EXTERNAL doesn't exists

**Comment by mvdan** [comment]
Surely you mean CONNECTIVITY_INTERNAL doesn't exist? It has to exist somewhere in that system. The question is whether you can obtain it.

In any case, I still don't see what can be done about this in the library. If you figure this out, it can be added as an FAQ to the README though.

**Comment by yleyvag** [comment]
when I add "<uses-permission
android:name="android.permission.CONNECTIVITY_INTERNAL" /> there's an
error label "Permission is only granted to system apps." I ran the app
with that permission, it still not working and the same exceptions.

**Comment by mvdan** [comment]
And have you tried making it a system app? I feel like you could figure this all out with Google.

**Comment by yleyvag** [comment]
No I didn't tried that, but it's something I shouldn't do, normal users will not make the app a system app. I Google it but I didn't fin anything. Maybe it's just a problem with Samsung devices.

**Comment by mvdan** [comment]
There's not much I can help with without a physical device to test, and I don't have a lot of free time. I'm going to close this for now, as it just seems like a limitation of the system shipped in that device. It doesn't look like the library can do anything to help here.
