### ISSUE TITLE
java.lang.NumberFormatException

### ISSUE THREAD

**Issue by antonderevyanko** [mvdan/libaccesspoint#9]
Caused by java.lang.NumberFormatException: Invalid int: "0x080027C446C0"
       at java.lang.Integer.invalidInt(Integer.java:137)
       at java.lang.Integer.parse(Integer.java:377)
       at java.lang.Integer.decode(Integer.java:187)
       at cc.mvdan.accesspoint.WifiApControl.macAddressToByteArray(WifiApControl.java:171)
       at cc.mvdan.accesspoint.WifiApControl.getDeviceName(WifiApControl.java:147)
       at cc.mvdan.accesspoint.WifiApControl.(WifiApControl.java)
       at cc.mvdan.accesspoint.WifiApControl.getInstance(WifiApControl.java:126)

**Comment by mvdan** [comment]
Please provide more information. What version of the library is this? What device? What Android version? What were you doing when this happened?

**Comment by mvdan** [comment]
Reopen if you have any more information; as is, there is little I can do.
